<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Subscribe_ng-tns-c18-15</name>
   <tag></tag>
   <elementGuidId>10b902ac-cb26-4230-80b3-5c024683b2a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.ng-tns-c18-15</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7395eb36-f9a2-4bf8-9dcd-bbd58a105152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c18-15</value>
      <webElementGuid>450d0702-03bc-4a3f-9b0c-3ba4389f45a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>86f931f9-cf09-444e-8097-3e0cf37dacba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>98979790-acbc-4049-bd27-3abea6f8a288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/component-assets/images/wizard-modal_close.svg</value>
      <webElementGuid>f0bbde4e-ef29-4bb9-b33b-13b15ee61886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/omnix-project[1]/omnix-main-master-page[@class=&quot;ng-tns-c1-3 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c1-3&quot;]/omnix-home[@class=&quot;ng-tns-c15-14 ng-star-inserted&quot;]/omnix-wizard-modal2[@class=&quot;ng-tns-c18-15 ng-tns-c15-14 ng-star-inserted&quot;]/div[@class=&quot;c-wizard-modal ng-tns-c18-15 ng-trigger ng-trigger-default ng-star-inserted&quot;]/div[@class=&quot;c-wizard-modal__dialog&quot;]/div[@class=&quot;c-wizard-modal__container&quot;]/a[@class=&quot;close-button&quot;]/img[@class=&quot;ng-tns-c18-15&quot;]</value>
      <webElementGuid>b620fd14-6b76-441e-b3df-291f876c0d94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='close']</value>
      <webElementGuid>f7ecdfa5-b1a9-4db6-986b-77c0d689ea53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//omnix-wizard-modal2/div/div/div/a/img</value>
      <webElementGuid>2bcc31cf-1876-4c0d-910d-bdd814b2d51f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'close' and @src = '/component-assets/images/wizard-modal_close.svg']</value>
      <webElementGuid>96862a04-7318-4d73-aa8f-c55c18b65fef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
