<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continue</name>
   <tag></tag>
   <elementGuidId>b54ad76a-82da-441c-bdc4-56437e47ce27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.o-btn--primary-blue.text-light.ng-tns-c28-101.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='submit-section']/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>769c1b8a-c66a-4014-bd63-9f0cba02de45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-btn--primary-blue text-light ng-tns-c28-101 ng-star-inserted</value>
      <webElementGuid>af1cb753-871e-48e4-8c4f-023e8e173afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Continue </value>
      <webElementGuid>5d5874c9-f8c1-4ee9-a558-7bd4e162392d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit-section&quot;)/a[@class=&quot;o-btn--primary-blue text-light ng-tns-c28-101 ng-star-inserted&quot;]</value>
      <webElementGuid>c3ba3500-7b8b-471f-95ba-5ab9415fd0c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='submit-section']/a[2]</value>
      <webElementGuid>666b405f-0a35-4351-aa18-f14b6ea296ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Continue')]</value>
      <webElementGuid>18f775c1-2800-4111-9e27-f0bb81ae529f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::a[1]</value>
      <webElementGuid>ffe347fe-103f-4478-bb18-91dc91f50902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/following::a[2]</value>
      <webElementGuid>a5792c79-6d34-4f84-a1ef-a69a3e0281a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy and Cookie Policy'])[1]/preceding::a[2]</value>
      <webElementGuid>b348e3a2-6ab6-4357-aac9-472420643061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I agree'])[1]/preceding::a[3]</value>
      <webElementGuid>eb24bf4a-974a-48d2-8e25-03842b5a1e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>121d2939-f335-437f-b43d-c6b1a998785c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/a[2]</value>
      <webElementGuid>ae548d7b-2084-42f9-bef8-68ff09e7bac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' Continue ' or . = ' Continue ')]</value>
      <webElementGuid>2f689eb5-6c8d-4f68-b2b8-952d6bb3b287</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
