<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ms</name>
   <tag></tag>
   <elementGuidId>96c98873-b0b8-4c2c-92a4-480c0a40789e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Ms.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cbd280ac-c682-4b3b-89ba-6e5f50eadcf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c39-125</value>
      <webElementGuid>efff7250-abad-4e14-90d2-4eb2aac42e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ms. </value>
      <webElementGuid>753da797-83a8-4be9-9601-76cc00d4a009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/omnix-project[1]/omnix-main-master-page[@class=&quot;ng-tns-c1-90 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c1-90&quot;]/omnix-guest-details[@class=&quot;ng-tns-c38-118 ng-star-inserted&quot;]/div[@class=&quot;guest-detail-component&quot;]/section[@class=&quot;c-tab ng-tns-c38-118 ng-trigger ng-trigger-default ng-star-inserted&quot;]/div[@class=&quot;c-tab__container ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;o-form_fullname&quot;]/div[@class=&quot;o-form_input required ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;o-form_input__dropdown ng-tns-c39-125 ng-trigger ng-trigger-down ng-star-inserted&quot;]/ul[@class=&quot;ng-tns-c39-125 ng-star-inserted&quot;]/li[@class=&quot;ng-tns-c39-125 ng-star-inserted&quot;]/a[@class=&quot;ng-tns-c39-125&quot;]</value>
      <webElementGuid>ff31b0a0-bc75-4f74-8fbd-3b7910c3f5b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ms.')]</value>
      <webElementGuid>95923323-a44e-4617-a3ce-72dcda361d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mr.'])[1]/following::a[1]</value>
      <webElementGuid>81bb1ba7-6bf3-4c85-982b-616d9338278c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::a[2]</value>
      <webElementGuid>9f456bb8-c7e9-4ae3-a2cb-cbc895f29a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First name'])[1]/preceding::a[1]</value>
      <webElementGuid>b1b6980c-522a-4f74-8025-0f13bc79f8d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ms.']/parent::*</value>
      <webElementGuid>6abd6b9f-c233-4767-bb80-c2823e53e80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li[2]/a</value>
      <webElementGuid>f9667b01-db15-48fe-a90a-297e72da4421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' Ms. ' or . = ' Ms. ')]</value>
      <webElementGuid>9e70eb55-f44c-47dc-ab67-b374c8d469cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
