<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search flights</name>
   <tag></tag>
   <elementGuidId>89fab999-5e20-469f-94f9-c55c609eda46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.o-btn.fixed-size.o-btn--primary-blue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5fddd1b7-d97c-4034-ae8d-d80fe5cbe22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-btn fixed-size o-btn--primary-blue</value>
      <webElementGuid>01ad5152-be11-45c1-96d1-49423bff9da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e4d3211b-3e8b-4792-8dc7-7c9d262d209c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>o-btn</value>
      <webElementGuid>1ceafeec-4ef6-4b62-8dac-65d0566c4e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>fixed-size</value>
      <webElementGuid>e4d41f6f-7af2-450d-904f-8cf9502a4904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Search flights
</value>
      <webElementGuid>863a8a40-5ece-41a8-96e0-c9e53fd3c611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/omnix-project[1]/omnix-main-master-page[@class=&quot;ng-tns-c1-3 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c1-3&quot;]/omnix-home[@class=&quot;ng-tns-c15-14 ng-star-inserted&quot;]/omnix-search-flight-modal[@class=&quot;ng-tns-c6-17 ng-tns-c15-14 ng-star-inserted&quot;]/div[@class=&quot;modal-search ng-tns-c6-17 ng-trigger ng-trigger-default ng-star-inserted&quot;]/div[@class=&quot;modal-search__body ng-valid ng-dirty ng-touched&quot;]/div[@class=&quot;c-search_submit&quot;]/div[@class=&quot;wrapper&quot;]/button[@class=&quot;o-btn fixed-size o-btn--primary-blue&quot;]</value>
      <webElementGuid>eb38187f-102b-40bd-92a5-b9e7f64e6806</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>78e8969c-274d-49de-9ee6-5b37ee3a8edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Children below 12 years old must travel with an adult companion aged 18 years old and above'])[1]/following::button[1]</value>
      <webElementGuid>4f6996b5-7f62-421e-bef5-96025eab9fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Children traveling on international flights'])[1]/following::button[1]</value>
      <webElementGuid>3896b8f9-c9b4-4fbc-a9f7-8e2799f8d870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOOK'])[1]/preceding::button[1]</value>
      <webElementGuid>f84c56dc-e26d-4ef0-8be4-d738df04a7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOOK'])[2]/preceding::button[1]</value>
      <webElementGuid>9f110f63-26e3-4b33-8fa4-aa846b8464a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/button</value>
      <webElementGuid>6821dcd2-72e2-4c61-b128-7a0f94161598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Search flights
' or . = ' Search flights
')]</value>
      <webElementGuid>702db93e-35f7-43b1-bc7e-1b1f2dcdccb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
