<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Help_ng-tns-c1-31 ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>6c3cd0f3-ca06-474d-976a-e2eaf75ae68c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.ng-tns-c1-31.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://www.cebupacificair.com/amplience-media/i/cebupacificair/ProjectSunrise-LinearColored-Resized-206x67?fmt=webp&amp;maxW=1920&amp;maxH=1920&amp;w=206&amp;h=67&amp;sm=c&amp;&amp;poi={$this.metadata.pointOfInterest.x},{$this.metadata.pointOfInterest.y},{$this.metadata.pointOfInterest.w},{$this.metadata.pointOfInterest.h}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>898e0d57-bd6a-456c-add5-a78e7beff18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c1-31 ng-star-inserted</value>
      <webElementGuid>751cfa69-0d9e-42c3-99c9-1785134090bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.cebupacificair.com/amplience-media/i/cebupacificair/ProjectSunrise-LinearColored-Resized-206x67?fmt=webp&amp;maxW=1920&amp;maxH=1920&amp;w=206&amp;h=67&amp;sm=c&amp;&amp;poi={$this.metadata.pointOfInterest.x},{$this.metadata.pointOfInterest.y},{$this.metadata.pointOfInterest.w},{$this.metadata.pointOfInterest.h}</value>
      <webElementGuid>416ba74b-c4f2-488d-8335-6f28bc02fc17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/omnix-project[1]/omnix-main-master-page[@class=&quot;ng-tns-c1-31 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c1-31&quot;]/header[@class=&quot;home-header logged-in ng-tns-c1-31 opened ng-star-inserted&quot;]/div[@class=&quot;home-header__main&quot;]/div[@class=&quot;home-header__main--container no-ads&quot;]/figure[@class=&quot;home-header__logo ng-tns-c1-31 ng-star-inserted&quot;]/img[@class=&quot;ng-tns-c1-31 ng-star-inserted&quot;]</value>
      <webElementGuid>cc624fd8-2527-4697-b9a2-8b0108e30e39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.cebupacificair.com/amplience-media/i/cebupacificair/ProjectSunrise-LinearColored-Resized-206x67?fmt=webp&amp;maxW=1920&amp;maxH=1920&amp;w=206&amp;h=67&amp;sm=c&amp;&amp;poi={$this.metadata.pointOfInterest.x},{$this.metadata.pointOfInterest.y},{$this.metadata.pointOfInterest.w},{$this.metadata.pointOfInterest.h}')]</value>
      <webElementGuid>e3941923-83ed-4d1b-848a-01e855538b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/figure/img</value>
      <webElementGuid>4a34ffb3-865a-449d-815f-8f9d6c3735bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.cebupacificair.com/amplience-media/i/cebupacificair/ProjectSunrise-LinearColored-Resized-206x67?fmt=webp&amp;maxW=1920&amp;maxH=1920&amp;w=206&amp;h=67&amp;sm=c&amp;&amp;poi={$this.metadata.pointOfInterest.x},{$this.metadata.pointOfInterest.y},{$this.metadata.pointOfInterest.w},{$this.metadata.pointOfInterest.h}']</value>
      <webElementGuid>e9647378-d20e-4fbb-9dd8-000b7373f4d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
