<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Subscribe_ng-tns-c18-15</name>
   <tag></tag>
   <elementGuidId>b3832d41-d943-4514-94dc-3f4d8b612d76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.ng-tns-c18-15</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b3892fa1-f954-4998-b2cc-cad404b7c5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c18-15</value>
      <webElementGuid>1d3176b6-79f6-4905-9d91-e00e88849166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>5dae9c5e-0570-4d16-b939-2b2fa1527d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>d42b330b-45b4-43b2-9a72-049c641ace6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/component-assets/images/wizard-modal_close.svg</value>
      <webElementGuid>f80b94a5-87ea-42ad-a1c2-7d5df7a790db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/omnix-project[1]/omnix-main-master-page[@class=&quot;ng-tns-c1-3 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c1-3&quot;]/omnix-home[@class=&quot;ng-tns-c15-14 ng-star-inserted&quot;]/omnix-wizard-modal2[@class=&quot;ng-tns-c18-15 ng-tns-c15-14 ng-star-inserted&quot;]/div[@class=&quot;c-wizard-modal ng-tns-c18-15 ng-trigger ng-trigger-default ng-star-inserted&quot;]/div[@class=&quot;c-wizard-modal__dialog&quot;]/div[@class=&quot;c-wizard-modal__container&quot;]/a[@class=&quot;close-button&quot;]/img[@class=&quot;ng-tns-c18-15&quot;]</value>
      <webElementGuid>5d7d2b05-35f4-4b55-8453-07a836612120</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='close']</value>
      <webElementGuid>f0490315-529f-4a97-9715-5d19d21a03a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//omnix-wizard-modal2/div/div/div/a/img</value>
      <webElementGuid>6831b00a-dd33-4a91-a983-ca0b3f9734cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'close' and @src = '/component-assets/images/wizard-modal_close.svg']</value>
      <webElementGuid>b2483c9d-3727-4012-8714-66dee9d46b0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
