<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_From_ng-tns-c19-19</name>
   <tag></tag>
   <elementGuidId>c4ae7a82-7445-4f35-95ff-a07650a44666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.clear-origin > img.ng-tns-c19-19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Clear']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1c897bc3-a89a-45e3-9b4e-df447b75a0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c19-19</value>
      <webElementGuid>2f6ab5bd-1ce6-4759-9540-13781d2ba976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Clear</value>
      <webElementGuid>4d06be59-3c3b-4914-84a7-f66fcfc48ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/component-assets/images/close-blue.svg</value>
      <webElementGuid>25220dfa-1447-48ef-a9e4-c7e9159c680b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/omnix-project[1]/omnix-main-master-page[@class=&quot;ng-tns-c1-3 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c1-3&quot;]/omnix-home[@class=&quot;ng-tns-c15-14 ng-star-inserted&quot;]/div[@class=&quot;hero&quot;]/div[@class=&quot;hero__search ng-tns-c15-14 ng-trigger ng-trigger-default ng-star-inserted&quot;]/div[@class=&quot;hero__search--group1 ng-tns-c16-16 ng-star-inserted&quot;]/div[@class=&quot;hero__search--destination&quot;]/div[@class=&quot;flight-journey&quot;]/div[@class=&quot;o-form_two-fields ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;o-form_input marker pin&quot;]/a[@class=&quot;clear-origin&quot;]/img[@class=&quot;ng-tns-c19-19&quot;]</value>
      <webElementGuid>ae9ad97c-9564-4d33-a5a3-072b891facd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Clear']</value>
      <webElementGuid>b79207eb-f022-4fb6-ad08-d2c675e15f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a/img</value>
      <webElementGuid>8a863d24-f1fe-4bb4-8980-f9df6f795883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Clear' and @src = '/component-assets/images/close-blue.svg']</value>
      <webElementGuid>cf47e70b-ccad-4b9d-8347-cb037f23e767</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
