<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Children_ng-tns-c24-23 grey ng-untouc_9074fa</name>
   <tag></tag>
   <elementGuidId>eb976b7d-68b7-4c5e-8dba-6a5efe46c368</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ng-tns-c24-23.grey.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[18]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21928c75-6eb6-41eb-aee3-ad52a6310d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c24-23 grey ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>6f8f4346-2aa6-4b8f-a9ec-eb8329c5d7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1eabccaa-7a4a-4242-ba8c-2b886487fc38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>number-only</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>822e0b6b-25ea-411e-ab2d-3669c1471ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c2ba584a-6a2c-4c08-affd-1c318c3efe4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>25d17c16-6857-4625-b8cc-4fe55b527e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>child</value>
      <webElementGuid>8145baef-773e-4fa4-9599-125098ff146a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-activate-number-only</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48f730de-f1f5-471c-aab3-aae67163fa4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>103</value>
      <webElementGuid>6998dbf4-d70d-4d07-a2bc-0e344f742a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/omnix-project[1]/omnix-main-master-page[@class=&quot;ng-tns-c1-3 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c1-3&quot;]/omnix-home[@class=&quot;ng-tns-c15-14 ng-star-inserted&quot;]/omnix-search-flight-modal[@class=&quot;ng-tns-c6-17 ng-tns-c15-14 ng-star-inserted&quot;]/div[@class=&quot;modal-search ng-tns-c6-17 ng-trigger ng-trigger-default ng-star-inserted&quot;]/div[@class=&quot;modal-search__body ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;c-search_info&quot;]/div[@class=&quot;pax-count o-form_guest&quot;]/div[@class=&quot;o-form_input marker&quot;]/input[@class=&quot;ng-tns-c24-23 grey ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>a615035d-079d-442e-8156-4163d53d11ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[18]</value>
      <webElementGuid>49df5a8f-8ce7-46dd-a0de-a0844cc5e30d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>dd06e182-50fb-4d39-a938-04344d22dbae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>97a2c789-3c81-4887-b0bc-d945872b7bc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
