<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Year_ng-tns-c40-126 ng-untouched ng-p_638fa2</name>
   <tag></tag>
   <elementGuidId>7e4dc39b-806d-4e57-bb35-60a1196177e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ng-tns-c40-126.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef5b41c2-321d-46c5-a0aa-5ef8a309121c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c40-126 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>4f6e9f07-8e88-49d6-a2f4-56d2bd9f1838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>year</value>
      <webElementGuid>61621e34-ff75-4edc-8030-7af167efdb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>83a103a5-a691-4355-81d0-5f3a429b34be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>number-only</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9cf7c52e-a5ec-40ae-87b0-da51d36f3bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>35ea446a-8951-43cd-9fd0-7cfa45067a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c33024e3-cc94-42fb-b920-a666dbd717fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>year</value>
      <webElementGuid>caddacc1-9914-4fde-bfef-07af6051df0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-activate-number-only</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>03ededef-8ae2-4fef-a4a7-8db2f608e1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>YYYY</value>
      <webElementGuid>48242456-790d-41e2-aefc-de942948705e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5eeba32f-e3ec-47da-b440-385f5167c3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/omnix-project[1]/omnix-main-master-page[@class=&quot;ng-tns-c1-90 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c1-90&quot;]/omnix-guest-details[@class=&quot;ng-tns-c38-118 ng-star-inserted&quot;]/div[@class=&quot;guest-detail-component&quot;]/section[@class=&quot;c-tab ng-tns-c38-118 ng-trigger ng-trigger-default ng-star-inserted&quot;]/div[@class=&quot;c-tab__container ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;o-form_date required&quot;]/div[@class=&quot;o-form_input required&quot;]/input[@class=&quot;ng-tns-c40-126 ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>9935eafb-942a-46a4-a4c8-eb65b4a1f0f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>156fc0d9-619c-4ab1-8663-9e2694bf2405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/input</value>
      <webElementGuid>3a4cdb01-19eb-4a51-afb6-07a5b4ca7162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'YYYY']</value>
      <webElementGuid>ad941f7f-336a-4c11-9cd0-6a0d302c407b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
