<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From_originFormControl-0</name>
   <tag></tag>
   <elementGuidId>dd0414c1-0c57-4fa2-ac4a-c6439ed55ffd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#originFormControl-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='originFormControl-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87ccf057-3e84-4487-a3c0-9d8d6ecbcdc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-truncate ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>5ad8c5e8-5223-406c-9790-49223b68803d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a9321169-96af-466b-9036-16808be7d864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be72b4e7-fa42-49df-8502-147304435f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>a38efe6d-0732-40d4-997b-6a5495923070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>originFormControl-0</value>
      <webElementGuid>0bf6e2c9-5c10-4668-baa5-c11592a66d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Origin</value>
      <webElementGuid>9e68511a-6f8d-401a-b407-6d6759be1bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>4fcea164-5325-44cc-ac9c-c37d5aca6408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;originFormControl-0&quot;)</value>
      <webElementGuid>be13abb7-3908-4840-90fa-6a2ec34eda1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='originFormControl-0']</value>
      <webElementGuid>10cda094-3864-411e-b383-852f0e452c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>36466cff-d3ea-4a0f-8252-e0fa24af6685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'originFormControl-0' and @placeholder = 'Select Origin']</value>
      <webElementGuid>2de76c34-32a8-4717-85df-fad2b5bc536c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
