<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Go Rewards Membership ID (Optional)_n_a7878d</name>
   <tag></tag>
   <elementGuidId>58912b99-1fba-403b-a5b3-4d08bd5882a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.o-form_input > input.ng-tns-c38-118.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75c535cc-c6c5-4be4-9214-4ee8e2c523be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c38-118 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>cab7419b-76bb-4756-9650-e9d734073212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>getGoNumber</value>
      <webElementGuid>0d7072a9-9057-4ab0-a79b-0e0e82efcdd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>number-only</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>650086eb-b6cf-412b-86c0-a80ae0f3a13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1992f26d-529a-4cac-a096-91f7471b1625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>c86bec73-0082-4508-a3ff-fa23db9ad7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>getGoNumber</value>
      <webElementGuid>d810fef7-0e97-47cd-ba05-f1674930fc92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-activate-number-only</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>950b825b-08a3-45a1-b6e1-9104a4f0c359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. 4041178445</value>
      <webElementGuid>3624edcd-4f32-4ce1-b9c1-eb372b01f6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>651db068-42b1-4f48-b961-026fdde8001d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>9f7d6cf5-cc31-4f04-8cc8-4775ee4ec83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/omnix-project[1]/omnix-main-master-page[@class=&quot;ng-tns-c1-90 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c1-90&quot;]/omnix-guest-details[@class=&quot;ng-tns-c38-118 ng-star-inserted&quot;]/div[@class=&quot;guest-detail-component&quot;]/section[@class=&quot;c-tab ng-tns-c38-118 ng-trigger ng-trigger-default ng-star-inserted&quot;]/div[@class=&quot;c-tab__container ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;o-form_getgo ng-tns-c38-118 ng-trigger ng-trigger-default ng-star-inserted&quot;]/div[@class=&quot;o-form_input&quot;]/input[@class=&quot;ng-tns-c38-118 ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>7185f77c-f275-4eec-8aea-a869f215d79a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[8]</value>
      <webElementGuid>41356ef8-ed8c-480e-9590-7b22068c523c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>e4b6f4b3-b15d-4646-ac60-12f1b9d15086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'e.g. 4041178445']</value>
      <webElementGuid>0a68dc0d-bf75-44b3-aa23-2e2e293d7d4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
