<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nationality_o-form_input__field ng-un_d9e3d9</name>
   <tag></tag>
   <elementGuidId>ea0967f1-1c0c-4ddc-a0c4-06d781e711ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.o-form_input__field.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>075c0915-4578-4950-8cfc-328390cc7933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-form_input__field ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>039aa6fb-25fb-4ee9-842d-a2a41a852d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>518df9e4-e2e5-4877-8c80-b8af11cf4279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>35d62905-5831-4525-8aea-c8d6b91545fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>nationality</value>
      <webElementGuid>e4253167-03b9-4fdf-bce6-595b8a057d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select nationality</value>
      <webElementGuid>2703d0ef-9a44-40d3-9aee-74fea58d8bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7d8d2249-c861-4370-8e2d-ae65d382c112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/omnix-project[1]/omnix-main-master-page[@class=&quot;ng-tns-c1-90 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c1-90&quot;]/omnix-guest-details[@class=&quot;ng-tns-c38-118 ng-star-inserted&quot;]/div[@class=&quot;guest-detail-component&quot;]/section[@class=&quot;c-tab ng-tns-c38-118 ng-trigger ng-trigger-default ng-star-inserted&quot;]/div[@class=&quot;c-tab__container ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;o-form_nationality&quot;]/div[@class=&quot;o-form_input required ng-invalid ng-touched ng-dirty&quot;]/input[@class=&quot;o-form_input__field ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>1420670b-a134-440a-85b3-b2a591196a33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[7]</value>
      <webElementGuid>283ea73c-dce5-46e0-9223-1b09430de5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>8b6882c3-64fe-4ddf-9560-753f42f55d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Select nationality']</value>
      <webElementGuid>bbdf6359-4896-4f88-8a01-429421727bd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
